function T = readCalkulateResultFile(file)
% readCalkulateResultFile  Reads a result file from AlkalinityAnalysis
%   READCALKULATERESULTFILE reads the .csv result file from an
%     AlkalinityAnalysis export (via calkulateDatasetToCSV) and returns the data
%     as a table.
%
%   Syntax
%     T = READCALKULATERESULTFILE(file)
%
%   Description
%     T = READCALKULATERESULTFILE(file) reads the .csv file at the fullpath file 
%       and returns it as a table T.
%
%   Example(s)
%     T = READCALKULATERESULTFILE('~/TA-measurement.results.csv')
%
%
%   Input Arguments
%     file - absolute path to file
%       char
%         The absolute path to the .csv file to read.
%
%
%   Output Arguments
%     T - output table
%       table
%         The data from the .csv file returned as a table.
%
%
%   Name-Value Pair Arguments
%
%
%   See also READTABLE
%
%   Copyright (c) 2022-2022 David Clemens (dclemens@geomar.de)
%
    
    if exist(file,'file') ~= 2
        error('Utilities:readCalkulateResultFile:FileNotExisting',...
            'The file ''%s'' is does not exist.',file)
    end
    
    % Define attributes
    %   Name                        Description     Units           formatSpec
    variableAttributes = {...
         'index',                   '',             '',             '%f';...
         'analysisBatch',           '',             '',             '%C';...
         'measurementType',         '',             '',             '%C';...
         'filePath',                '',             '',             '%s';...
         'fileName',                '',             '',             '%s';...
         'fileGood',                '',             '',             '%s';...
         'referenceGood',           '',             '',             '%s';...
         'salinity',                '',             'PSU',          '%f';...
         'analyteVolume',           '',             'mL',           '%f';...
         'dic',                     '',             'µmol kg-1',    '%f';...
         'titrant',                 '',             '',             '%C';...
         'titrantAmountUnit',       '',             '',             '%C';...
         'molinityHCl',             '',             'mol L-1',      '%f';...
         'molinityNaCl',            '',             'mol L-1',      '%f';...
         'alkalinityCertified',     '',             'µmol kg-1',    '%f';...
         'emf0Guess',               '',             'mV',           '%f';...
         'sampleId',                '',             '',             '%s';...
         'titrationStart',          '',             '',             '%D';...
         'titrationDuration',       '',             'min',          '%s';...
         'analyteMass',             '',             'kg',           '%f';...
         'titrantMolinity_here',    '',             'mol L-1',      '%f';...
         'titrantMolinity',         '',             'mol L-1',      '%f';...
         'status',                  '',             '',             '%C';...
         'alkalinity',              '',             'µmol kg-1',    '%f';...
         'alkalinityGran',          '',             'µmol kg-1',   	'%f';...
         'alkalinityGran_estimate', '',             'µmol kg-1',   	'%f';...
         'alkalinityNPoints',       '',             '',             '%f';...
         'alkalinityStd',           '',             'µmol kg-1',  	'%f';...
         'emf0',                    '',             'mV',           '%f';...
         'emf0Gran',                '',             'mV',           '%f';...
         'emf0GranEstimate',        '',             'mV',           '%f';...
         'pHInitial',               '',             '',             '%f';...
         'temperatureInitial',      '',             '°C',           '%f';...
         'alkalinityOffset',        '',             'µmol kg-1',    '%f'};
    
    % The column format spec
    formatSpec = cat(2,variableAttributes{:,4});
        
    % Read the data
	T = readtable(file,...
        'FileType',             'text',...
        'Delimiter',            ';',...
        'Encoding',             'ISO-8859-2',...
        'Format',               formatSpec,...
        'ReadVariableNames',	true);
    
    % Assign attributes
    T.Properties.VariableNames = variableAttributes(:,1);
    T.Properties.VariableDescriptions = variableAttributes(:,2);
    T.Properties.VariableUnits = variableAttributes(:,3);
    
    % Modify time format
    T.titrationStart.Format = 'dd.MM.yyyy HH:mm:ss';
    
    % Modify duration
    tokens = regexp(T{:,'titrationDuration'},'^(\d+)\sdays\s(\d{2}):(\d{2}):(\d{2})$','tokens');
    tokens = cat(1,tokens{:});
    tokens = str2double(cat(1,tokens{:}));
    T.titrationDuration = duration(24.*tokens(:,1) + tokens(:,2),tokens(:,3),tokens(:,4));
    
    % Modify booleans
    T.fileGood = str2logical(T{:,'fileGood'});
    T.referenceGood = str2logical(T{:,'referenceGood'});
    
    % Modify status
    tokens = regexp(cellstr(T{:,'status'}),'\[[\d;]+m([A-Za-z]+)','tokens');
    tokens = cat(1,tokens{:});
    T.status = categorical(cat(1,tokens{:}));
    
    function l = str2logical(str)
        l = cellfun(@(x) strcmp(x,'True'),str);
    end
end
